//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadConsultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialClinico
    {
        public int id { get; set; }
        public int idPaciente { get; set; }
        public int idCita { get; set; }
        public string diagnostico { get; set; }
        public string tratamiento { get; set; }
        public System.DateTime fecha { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
